version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: meu-personal-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - meu-personal-network
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: meu-personal-api
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
    depends_on:
      - redis
    volumes:
      - ./apps/api/uploads:/app/uploads
    restart: unless-stopped
    networks:
      - meu-personal-network

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: meu-personal-web
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - meu-personal-network

volumes:
  redis_data:

networks:
  meu-personal-network:
    driver: bridge